// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOiexboS58gQnpQYoB0y0n2pFmcfrTURE',
    appId: '1:1048736847617:web:9c7a26034721a8591c2d00',
    messagingSenderId: '1048736847617',
    projectId: 'ubify-5304a',
    authDomain: 'ubify-5304a.firebaseapp.com',
    storageBucket: 'ubify-5304a.firebasestorage.app',
    measurementId: 'G-EXXCRRJMJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxYrZde5x5wDTNDG7YwPranc1YrQowgw',
    appId: '1:1048736847617:android:5911c9e2cbcadcf71c2d00',
    messagingSenderId: '1048736847617',
    projectId: 'ubify-5304a',
    storageBucket: 'ubify-5304a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHSr7AgRD0rCfpa3mXXRhiYPizRYpeFE',
    appId: '1:1048736847617:ios:91c347582df2c08e1c2d00',
    messagingSenderId: '1048736847617',
    projectId: 'ubify-5304a',
    storageBucket: 'ubify-5304a.firebasestorage.app',
    iosBundleId: 'com.example.ubify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHSr7AgRD0rCfpa3mXXRhiYPizRYpeFE',
    appId: '1:1048736847617:ios:91c347582df2c08e1c2d00',
    messagingSenderId: '1048736847617',
    projectId: 'ubify-5304a',
    storageBucket: 'ubify-5304a.firebasestorage.app',
    iosBundleId: 'com.example.ubify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOiexboS58gQnpQYoB0y0n2pFmcfrTURE',
    appId: '1:1048736847617:web:61eac74e4870201a1c2d00',
    messagingSenderId: '1048736847617',
    projectId: 'ubify-5304a',
    authDomain: 'ubify-5304a.firebaseapp.com',
    storageBucket: 'ubify-5304a.firebasestorage.app',
    measurementId: 'G-SM35WVZGR1',
  );
}
